delete action implemented
santiment/app pull request #2466
Opened 2022-04-22 09:56 UTC by peratik

## Changes
- Delete action implemented
- Confirm delete dialog added
- Loading state added

## Notion's card

## Checklist

- [x] I've performed a self-review, followed all rules from [Frontend style guide](https://www.notion.so/santiment/Front-end-style-guide-81750096b38c4bea9a29b14fd4ab8667)
- [x] If I make changes to another person's module, I've asked how to use it or request a review
- [x] I've updated the [documentation](https://github.com/santiment/academy), if necessary (Keyboard shortcuts, Account settings)
- [x] I've checked night mode, mobile & tablet screens (if have changes in UI)
- [x] I've added tests (if necessary)

## Screenshots or GIFs

2022-04-22 12:00 UTC, DmitriVanGuard requested changes

2022-04-22 12:00 UTC, DmitriVanGuard commented on src/pages/Explorer/Components/api/delete.js
> +export default (id, deleteKey) => mutate(DELETE[deleteKey](id))
```suggestion
function DELETE_ENTITY_MUTATION(id, type) {
  let data = 'id'
  let mutation = 'removeWatchlist'

  switch (type) {
    case Something.CHART:
      mutation = 'deleteChartConfiguration'
      break
    case Something.TRIGGER:
      mutation = 'removeTrigger'
      data = 'trigger { id }'
  }

  return `mutation {
    ${mutation}(id:${id}){
      ${data}
    }
  }`
}

export const mutateDeleteEntity = (id, type) => mutate(DELETE_ENTITY_MUTATION(id, type))
```

2022-04-22 12:00 UTC, DmitriVanGuard commented on src/pages/Explorer/Components/DeleteConfirmationDialog.svelte
> +            .then(closeDialog)}>Delete</button
```suggestion
        on:click={onDeleteClick}>Delete</button
```

2022-04-22 12:00 UTC, DmitriVanGuard commented on src/pages/Explorer/Components/DeleteConfirmationDialog.svelte
> +    <div class="column hv-center body-2 c-waterloo mrg--b mrg-xl">
1. `column` is redundant;
2. `[D-0-1]` Change the order of the margin classes: 1) `mrg-[size]` 2) `mrg-[side]`

2022-04-22 12:00 UTC, DmitriVanGuard commented on src/pages/Explorer/Components/DeleteConfirmationDialog.svelte
> +    <div class="row justify v-center h4 txt-m mrg--b mrg-s c-black">
Same as the `[D-0-1]`

2022-04-22 12:00 UTC, DmitriVanGuard commented on src/pages/Explorer/Components/DeleteConfirmationDialog.svelte
> +        class="btn-1 mrg--r mrg-m"
Same as the `[D-0-1]`

2022-04-22 12:00 UTC, DmitriVanGuard commented on src/pages/Explorer/Components/DeleteConfirmationDialog.svelte
> +            .then((id) => onComplete(id))
`.then(onComplete)`

2022-04-22 12:00 UTC, DmitriVanGuard commented on src/pages/Explorer/Components/Actions.svelte
> +      () => document.getElementById(`${getItemId(item, type)}`).parentElement.remove(),
Filter the array that contains this item.

2022-04-22 12:00 UTC, DmitriVanGuard commented on src/pages/Explorer/Components/Actions.svelte
> +    e.preventDefault()
`[D-0-2]` Use the [`|preventDefault`](https://svelte.dev/docs#template-syntax-element-directives-on-eventname) modifier

2022-04-22 12:00 UTC, DmitriVanGuard commented on src/pages/Explorer/Components/Actions.svelte
> +    e.preventDefault()
Same as the `[D-0-2]`

2022-04-22 12:00 UTC, DmitriVanGuard commented on src/pages/Explorer/Category/UserCreation.svelte
> +      e.preventDefault()
Same as the `[D-0-2]`

2022-04-22 12:17 UTC, peratik commented on src/pages/Explorer/api.js
> +  return query(QUERY, { cache: false }).then(accessor)
Is 20 sec good?

2022-04-22 13:02 UTC, DmitriVanGuard commented on src/pages/Explorer/Category/UserCreation.svelte
> +    if (['use', 'svg'].indexOf(e.target.tagName) > -1) {
```suggestion
    if (['use', 'svg'].includes(e.target.tagName)) {
```

2022-04-22 13:02 UTC, DmitriVanGuard commented on src/pages/Explorer/api.js
> +  return query(QUERY, { cache: false }).then(accessor)
Yes

2022-04-25 08:01 UTC, DmitriVanGuard requested changes

2022-04-25 13:09 UTC, DmitriVanGuard requested changes

2022-04-25 13:09 UTC, DmitriVanGuard commented on src/pages/Explorer/index.svelte
>    }
```css
main, .aside {
   position: sticky;
   bottom: 0;
   align-self: flex-end;
}
```

2022-04-26 08:37 UTC, DmitriVanGuard requested changes

2022-04-26 08:37 UTC, DmitriVanGuard commented on src/pages/Explorer/index.svelte
> +    min-height: 100%;
```suggestion
```

2022-04-26 09:18 UTC, merged