explorere items views added
santiment/app pull request #2607
Opened 2022-09-29 08:32 UTC by peratik

## Changes
- styles updated
- queries updated
- views added

## Notion's card
https://www.notion.so/santiment/Explorer-post-views-70492ee03eff47cfb3bba24f39410038

## Checklist

- [x] I've performed a self-review, followed all rules from [Frontend style guide](https://www.notion.so/santiment/Front-end-style-guide-81750096b38c4bea9a29b14fd4ab8667)
- [x] If I make changes to another person's module, I've asked how to use it or request a review
- [x] I've updated the [documentation](https://github.com/santiment/academy), if necessary (Keyboard shortcuts, Account settings)
- [x] I've checked night mode, mobile & tablet screens (if have changes in UI)
- [x] I've added tests (if necessary)

## Screenshots or GIFs

![image](https://user-images.githubusercontent.com/6568353/192981863-d31e94fc-4a15-4ab1-8b54-7e10d2cd648c.png)

2022-09-29 08:35 UTC, DmitriVanGuard approved these changes

2022-09-29 09:38 UTC, peratik commented
We should wait until backend issue related to views get resolved.

2022-09-30 09:33 UTC, DmitriVanGuard requested changes
Use webkit's notifications store `import { notifications$ } from '@/ui/Notifications'`

2022-09-30 09:33 UTC, DmitriVanGuard commented on src/pages/Explorer/Components/ActionButton.svelte
> +  export let forceactive = false
camelCase

2022-09-30 09:33 UTC, DmitriVanGuard commented on src/pages/Explorer/Components/ActionButton.svelte
> +    class="actionbutton row hv-center {forceactive ? '$style.forceactive' : ''}"
Use `class:[className]` [directive](https://svelte.dev/docs#template-syntax-element-directives-class-name)

2022-10-03 10:20 UTC, DmitriVanGuard requested changes

2022-10-03 10:20 UTC, DmitriVanGuard commented on src/pages/Explorer/Components/EditDialog.svelte
> +        })
This error dispatcher is duplicated in multiple places (`src/pages/Explorer/Category/ExplorerCategory.svelte`, `src/pages/Explorer/Category/Widget.svelte`, etc). Move it to the function and reuse it

2022-10-03 11:02 UTC, DmitriVanGuard approved these changes

2022-10-05 09:16 UTC, merged