Added NFT Influencers table - mobile view
santiment/app pull request #2625
Opened 2022-10-17 21:45 UTC by Woafflation

## Changes

1. Added Nft Influencers Transactions table under new root "/nft" for Mobile view
 1.1 Created Table component with new view
 1.2 Added Row component with adjustable Info component
 1.3 Added links and addresses with copy func
 1.4 Added popup about sanbase desktop version
2. Added simplified table into Market page

## Notion's card

https://www.notion.so/santiment/Nft-table-on-mobile-f7d759e5bcdd438d8646bd3a8bcb9720

## Checklist

- [ ] I've performed a self-review, followed all rules from [Frontend style guide](https://www.notion.so/santiment/Front-end-style-guide-81750096b38c4bea9a29b14fd4ab8667)
- [ ] If I make changes to another person's module, I've asked how to use it or request a review
- [ ] I've updated the [documentation](https://github.com/santiment/academy), if necessary (Keyboard shortcuts, Account settings)
- [ ] I've checked night mode, mobile & tablet screens (if have changes in UI)
- [ ] I've added tests (if necessary)

## Screenshots or GIFs

![Снимок экрана 2022-10-18 в 00 41 56](https://user-images.githubusercontent.com/46782114/196289830-461a5194-d2f3-400a-9cb6-16720d4a8482.png)
![Снимок экрана 2022-10-18 в 00 41 53](https://user-images.githubusercontent.com/46782114/196289836-f7557518-cc54-49b5-b798-bd471b6032a4.png)
![Снимок экрана 2022-10-18 в 00 41 47](https://user-images.githubusercontent.com/46782114/196289841-7fbb2c97-830c-47bf-830e-f7afe994e549.png)
![Снимок экрана 2022-10-18 в 00 41 38](https://user-images.githubusercontent.com/46782114/196289845-bb401175-245c-49a4-8fb7-6532da0df9d7.png)

2022-10-18 08:43 UTC, DmitriVanGuard requested changes

2022-10-18 08:43 UTC, DmitriVanGuard commented on src/pages/NftInfluencersTrx/Table/MarketTable.js
> +  )
It has similar structure to `Social Trends` table (`src/ducks/TrendsTable/index.js`), hence it should be reused

2022-10-18 08:43 UTC, DmitriVanGuard commented on src/pages/NftInfluencersTrx/Table/Row/Info/Info.js
> +  })
Use webkit's `dateDifferenceInWords(from)`

2022-10-18 08:43 UTC, DmitriVanGuard commented on src/pages/NftInfluencersTrx/Table/Row/Info/Info.js
> +  const when = dateDifferenceInWords({
Declaration order:
1. Props destructuring and variables;
2. Hooks and effects;
3. Functions;

2022-10-18 08:43 UTC, DmitriVanGuard commented on src/pages/NftInfluencersTrx/Table/Row/Info/Info.js
> +}
Create a `Section` component this will accept `title` and `children` props

2022-10-18 08:43 UTC, DmitriVanGuard commented on src/pages/NftInfluencersTrx/Table/Row/Info/Info.js
> +    if (clearTimerRef.current) clearTimerRef.current()
Timer should be cleared on the unmount as well

2022-10-18 08:43 UTC, DmitriVanGuard commented on src/pages/NftInfluencersTrx/Table/Row/Info/Info.js
> +    const node = document.getElementById(address)
Elements' `id` is not needed since the data can be accessed using `e.currentTarget.textContent`

2022-10-18 08:43 UTC, DmitriVanGuard commented on src/pages/NftInfluencersTrx/Table/Row/Info/Info.module.scss
> +  --bg-hover: var(--green-light-1) !important;
`!important` will not be needed if `btn` class is assigned instead of `btn-0`

2022-10-18 08:43 UTC, DmitriVanGuard commented on src/pages/NftInfluencersTrx/Table/Row/Info/Info.js
> +            <span className='nowrap line-clamp'>{nft.contractAddress}</span>
Just `.single-line`

2022-10-18 08:43 UTC, DmitriVanGuard commented on src/pages/NftInfluencersTrx/Table/Row/Info/Info.js
> +            <span className='nowrap line-clamp'>{trxHash}</span>
Just `.single-line`

2022-10-18 08:43 UTC, DmitriVanGuard commented on src/pages/NftInfluencersTrx/Table/Table.js
> +  </table>
```jsx
<div class='influencers'>
   <div class='header row justify txt-m c-casper'>
         <span>...</span>
         ...
   </div>
   {rows.map(data => (
      <div>
           <div class="row justify body-2>...</div>
           <Info />
      </div>
   )}
</div>
```

2022-10-18 13:29 UTC, Woafflation commented on src/pages/NftInfluencersTrx/Table/Table.js
> +        <Row key={formatKey(trx, idx)} data={trx} />
It has to be, because there are some multiple buys/sells with the same transaction hash

2022-10-19 06:32 UTC, DmitriVanGuard requested changes

2022-10-19 06:32 UTC, DmitriVanGuard commented on src/pages/NftInfluencersTrx/Table/Row/Row.js
> +  }
To increase readability, move the market-related code to the standalone component

2022-10-19 06:32 UTC, DmitriVanGuard commented on src/pages/NftInfluencersTrx/Table/Table.js
> +      {!isMarket && (
To increase readability, move the market-related code to the standalone component

2022-10-19 11:44 UTC, DmitriVanGuard approved these changes

2022-10-19 17:28 UTC, merged